version: '3.7'


services:
    database:
        build:
            context: docker/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306'


    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            -   .:/var/www/hobby-box.nl
        user: '1000'


    nginx:
        build:
            context: docker/nginx
        ports:
            -   80:80
        volumes:
            -   .:/var/www/hobby-box.nl

    composer:
        restart: 'no'
        image: composer:latest
        command: install
        volumes:
            -   .:/app


#    traefik:
#        image: 'traefik:v2.4'
#        container_name: 'traefik'
#        command:
#            #- "--log.level=DEBUG"
#            - "--api.insecure=true"
#            - "--providers.docker=true"
#            - "--providers.docker.exposedbydefault=false"
#            - "--entrypoints.web.address=:80"
#        ports:
#        - '80:80'
#        - '8080:8080'
#        volumes:
#        - '/var/run/docker.sock:/var/run/docker.sock:ro'
#
#    whoami:
#        image: "traefik/whoami"
#        container_name: "simple-service"
#        labels:
#            - "traefik.enable=true"
#            - "traefik.http.routers.whoami.rule=Host(`www.hobby-box.nl`)"
#            - "traefik.http.routers.whoami.entrypoints=web"
#            - 'traefik.http.routers.my-app.tls=true'
#            - 'traefik.http.routers.my-app.tls.certresolver=lets-encrypt'
#

#    mailhog:
#        image: mailhog/mailhog:latest
#        restart: always
#        ports:
#            - 1025:1025 #smtp server
#            - 8025:1025 #web ui